columnSuffix: xmebpuze
contentColumnType: text
fieldGroup: cabf5db1-8ddc-4576-b387-39d4366462cd # Message
handle: speaker
instructions: null
name: Speaker
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
